# Generated by Django 5.1.4 on 2024-12-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_course_created_at_remove_course_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='True', max_length=100, unique=True),
        ),
    ]
