# Generated by Django 5.1.4 on 2024-12-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_course_created_at_course_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
