# Generated by Django 5.1.4 on 2024-12-11 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
