# Generated by Django 5.1.4 on 2024-12-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='E518lBz6OIBMDhYdJubhJtvUarusEbtk', editable=False, max_length=32, unique=True),
        ),
    ]
