# Generated by Django 5.1.4 on 2024-12-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='PasswordResetRequest',
        ),
    ]
